version: "3.8"

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  # ───────────────────────── DNS BACKEND ─────────────────────────
  coredns:
    image: coredns/coredns:1.12.2   # актуальный stable tag
    container_name: coredns
    restart: unless-stopped
    command: ["-conf", "/Corefile"]
    volumes:
      - ./coredns/Corefile:/Corefile:ro
    networks: [backend]

  dnsdist:
    image: powerdns/dnsdist-19:1.9.5 # stable 1.9.x line
    container_name: dnsdist
    restart: unless-stopped
    volumes:
      - ./dnsdist/dnsdist.conf:/etc/dnsdist/dnsdist.conf:ro
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "853:853/tcp"   # DoT
      - "8443:8443"     # DoH (чтоб не забрать 443)
    networks: [frontend, backend]

  # ──────────────────────── DATABASE LAYER ───────────────────────
  postgres:
    image: postgres:16-alpine
    container_name: npm-postgres
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER:     ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB:       ${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks: [frontend]

  # ───────────────────── NGINX PROXY MANAGER ─────────────────────
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:2.12.6
    container_name: npm
    depends_on: [postgres]
    restart: unless-stopped
    env_file: .env
    environment:
      DB_POSTGRES_HOST:     postgres
      DB_POSTGRES_PORT:     5432
      DB_POSTGRES_USER:     ${POSTGRES_USER}
      DB_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_POSTGRES_NAME:     ${POSTGRES_DB}
      INITIAL_ADMIN_EMAIL:  ${NPM_ADMIN_EMAIL}
      INITIAL_ADMIN_PASSWORD: ${NPM_ADMIN_PASSWORD}
    volumes:
      - ./data/npm/data:/data
      - ./data/npm/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"   # HTTPS для сайтов
      - "81:81"     # UI
    networks: [frontend]

  # ────────────────────── REACT PLACEHOLDER ──────────────────────
  leanwebstudio-web:
    build: ./react-app        # см. Dockerfile
    container_name: leanwebstudio-web
    restart: unless-stopped
    expose: ["3000"]
    networks: [frontend]
